name: MicroService CD

on:
  push:
    branches: [production]

jobs:

  detect-changes:
    uses: ./.github/workflows/detect-changes.yml

  docker-build-push:
    name: Build & Push Docker Images
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.any_changed == 'true' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ${{ fromJson(needs.detect-changes.outputs.services_json) }}
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push ${{ matrix.service }}
        run: |
          cd ${{ matrix.service }}
          docker build -t thuan410/${{ matrix.service }}:latest .
          docker build -t thuan410/${{ matrix.service }}:${{ github.sha }} .
          docker push thuan410/${{ matrix.service }}:latest
          docker push thuan410/${{ matrix.service }}:${{ github.sha }}